### PR TITLE
Add `rsvp add to calendar` command

### PR DESCRIPTION
**Pull request by alexandrinaw**
Adds a new feature, `rsvp add to calendar`, that will create an event on the calendar defined by the environment variable `GOOGLE_CALENDAR_ID`.
- The "location" of the event is whatever was set by `rsvp set place`
- The event must have a `time` and `date`
- The event must also have a `duration` (new thing).
  - `rsvp set duration 0:30` and `rsvp set duration 30m` will both work
- The calendar event's description will have a link to the zulip conversation that created it
- People who RSVP'd to the event will be added as attendees, so the calendar events will show up on their personal calendars if they use gcal
  - There will _not_ be an email invite sent 
- RSVPBot will reply to `rsvp add to calendar` with a link to the calendar event.

Whenever one of these things is changed, the calendar event will be updated with the new details.

### CODE REVIEW

**Comment by alexandrinaw** [comment]
@kokeshii There will be a little bit of work to get this set up when you deploy -- Either I'll have to transfer the credentials I've already created to you, or you can set them up on your own. Either way, they'll both have to be added as env variables. LMK which one you prefer.

**Comment by wtfcarlos** [comment]
@alexandrinaw THANK YOU!

Since this is a big functionality update to RSVPBot, I would like to review this in person with you. I'm busy this week, but we'll schedule a time to meet at RC and go over this PR.

SO EXCITED!

**Comment by alexandrinaw** [comment]
@kokeshii sounds good 😄

**Comment by alexandrinaw** [comment]
ping @kokeshii when do you want to go over this?

**Comment by wtfcarlos** [comment]
@alexandrinaw Sorry! I've been busy with work and social events. 

It's gonna be hard for me to find time to go to RC after work this week and next week. Want to outline a deploy guide with the steps that I should take so I can deploy this over the weekend? I'll merge the PR right now

**Pull request merged**
