### PR TITLE
Decision aliases

### PR DESCRIPTION
**Pull request by alexandrinaw**
cc @amul531, who I paired with on this 🎉 

Adds the following options for `rsvp <decision>`. _**note**: these are just examples. the possibilities are limitless_ 😄 
#### decision == yes
- yessssss
- yas
- yasssss
- in
- yeah
- yeahhhhh
- yep
#### decision == no
- noooooooooooo
- out
- nope
- nah
- nahhhhhh

### CODE REVIEW

**Comment by kokeshii** [comment]
https://33.media.tumblr.com/35c41f02b43daf6f4596c7c7634fbe55/tumblr_inline_nkmbd8CLpq1qdopp2.gif

**Comment by wtfcarlos** [comment]
image

**Comment by wtfcarlos** [comment]
YASSSS GAWWD!!!

**Comment by wtfcarlos** [comment]
Thank you @alexandrinaw and @amul531

**Pull request merged**
